services:
  db:
    image: mariadb:10-focal
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306

  backend:
    build:
      context: backend
    restart: always
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/code  # Bind mount for hot reloading
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - frontnet

  frontend:
    build:
      context: frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - frontnet
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Bind mount for hot reloading

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
