cards = [
    (
        "Flames of the Forgotten",
        "Unleash fiery wrath upon your foes.",
        15,
        "/lotus.png",
    ),
    (
        "Eternal Nightshade",
        "Shroud the battlefield in eternal darkness.",
        20,
        "/lotus.png",
    ),
    (
        "Mystic Phoenix",
        "Rebirth from ashes with untold power.",
        25,
        "/lotus.png",
    ),
    (
        "Veil of Illusions",
        "Conjure a world of mesmerizing illusions.",
        12,
        "/lotus.png",
    ),
    (
        "Arcane Sanctum",
        "Tap into ancient arcane energy.",
        18,
        "/lotus.png",
    ),
    ("Chronomancer's Relic", "Bend time to your will.", 22, "/lotus.png"),
    (
        "Soulbinder's Pact",
        "Bind the souls of the fallen to your command.",
        30,
        "/lotus.png",
    ),
    (
        "Serpent's Embrace",
        "Harness the cunning and power of serpents.",
        17,
        "/lotus.png",
    ),
    (
        "Stormbringer's Call",
        "Summon the fury of a raging storm.",
        24,
        "/lotus.png",
    ),
    (
        "Grove of Whispering Winds",
        "Listen to the secrets of the ancient forest.",
        13,
        "/lotus.png",
    ),
    (
        "Celestial Beacon",
        "Guide your path with celestial light.",
        19,
        "/lotus.png",
    ),
    (
        "Shadowblade Assassin",
        "Strike from the shadows with deadly precision.",
        16,
        "/lotus.png",
    ),
    (
        "Lunar Eclipse",
        "Harness the power of the moon's shadow.",
        21,
        "/lotus.png",
    ),
    (
        "Elemental Convergence",
        "Unite the elements for ultimate control.",
        23,
        "/lotus.png",
    ),
    (
        "Infernal Dragon",
        "Release the fury of an infernal dragon.",
        28,
        "/lotus.png",
    ),
    (
        "Sapphire Enchantress",
        "Weave spells of beauty and destruction.",
        26,
        "/lotus.png",
    ),
    (
        "Netherworld Gatekeeper",
        "Guard the passage to the nether realms.",
        29,
        "/lotus.png",
    ),
    (
        "Crimson Dawn",
        "Awaken to a new world bathed in crimson light.",
        14,
        "/lotus.png",
    ),
    (
        "Frostfire Wyrm",
        "Unleash a chilling blaze upon your enemies.",
        27,
        "/lotus.png",
    ),
    (
        "Phantom Mirage",
        "Dance with phantoms that fade into the ether.",
        11,
        "/lotus.png",
    ),
    (
        "Eldritch Ritual",
        "Perform ancient rites to gain power.",
        22,
        "/lotus.png",
    ),
    (
        "Spirit of the Wild",
        "Embrace the primal spirit within.",
        18,
        "/lotus.png",
    ),
    (
        "Voidwalker",
        "Traverse the void between worlds.",
        25,
        "/lotus.png",
    ),
    (
        "Ironclad Golem",
        "Stand strong as an iron sentinel.",
        20,
        "/lotus.png",
    ),
    (
        "Arcane Echo",
        "Echo the arcane spells of your foes.",
        19,
        "/lotus.png",
    ),
    (
        "Ethereal Guardian",
        "Protect with the might of ethereal forces.",
        24,
        "/lotus.png",
    ),
    (
        "Twilight Sorcerer",
        "Control the twilight with mystical power.",
        21,
        "/lotus.png",
    ),
    (
        "Emberwing Falcon",
        "Soar on wings of fire and ash.",
        23,
        "/lotus.png",
    ),
    (
        "Glimmering Sprite",
        "Enchant with a touch of fairy magic.",
        14,
        "/lotus.png",
    ),
    (
        "Ravenous Ghoul",
        "Feed on the energy of the living.",
        16,
        "/lotus.png",
    ),
]
